[project]
name = "polar-dashboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "plotly>=6.7.0",
    "pyarrow>=24.0.0",
    "ruff>=0.15.12",
    "scipy>=1.17.1",
    "streamlit>=1.57.0",
    "watchdog>=6.0.0",
]
